blank_issues_enabled: true
contact_links:
  - name: Contributing Guidelines
    url: https://github.com/rhejos/Compliance-Repo/blob/main/CONTRIBUTING.md
    about: Read our contribution guidelines before submitting
